- docs/docker-tsurugi_ja.md
- docs/getting-started.md
- docs/getting-started_ja.md
typo 修正と SQL を多く含む fenced code block の syntax を `sql` へ変更します。
> doc: fix typos and syntax highlighting

- docs/upgrade-guide.md
This PR added "trouble shooting" section to "Tsurugi Upgrade Guide", including instruction for "SCD-00402: unsupported service message."
Note that it seems that refer to detail documents are not enough in individual sections.
links to each heading:
* https://github.com/project-tsurugi/tsurugidb/blob/docs-upgrade-troubleshoot/docs/upgrade-guide.md#no-response
* https://github.com/project-tsurugi/tsurugidb/blob/docs-upgrade-troubleshoot/docs/upgrade-guide.md#service-not-registered
* https://github.com/project-tsurugi/tsurugidb/blob/docs-upgrade-troubleshoot/docs/upgrade-guide.md#inconsistent-message
> docs: add trouble shooting to upgrade guide.

- README.md
- docs/README.md
This PR introduces index of documents in this repository as [docs/README.md](https://github.com/project-tsurugi/tsurugidb/blob/58bd099b0e3f75ddcc62e156b16c31a9188c6d24/docs/README.md).
> docs: add document index.

- dist/install/install.sh
ユーザがオプション指定するつづりを間違えて install.sh を実行した時など、未知のオプションが渡ってきたときに、現在は無視されていますが、これをエラー終了すように変更する修正です。
```
$ ./install.sh --prefix=/home/ban/build/b --build_type=Debug
[ERROR] invalid option: --build_type=Debug
```
> make install.sh to reject invalid options

- docs/sql-features.md
sql-features.md に現状での制限事項「TIME WITH TIME ZONE と TIMESTAMP WITH TIME ZONE がサポートするタイムゾーンは UTCのみ」であることを明記します。
> docs: supporting only UTC for time zone

- docs/sql-features.md
IS [NOT] TRUE/FALSE is unsupported on BETA5. The doc change to remove related lines from sql-features.md.
> docs: remove IS TRUE/FALSE operator from sql-features.md

- docs/sql-features.md
This PR adds syntax rules of extra boolean expressions like `x is {true, false, unknown}`  to the document SQL Feature list.
> doc: reference of boolean tests.

- docs/sql-features.md
This PR adds syntax rules of binary types (`BINARY`, `VARBINARY`, and their literals) to the document SQL Feature list.
> doc: reference of binary type.

- docs/sql-features.md
This PR adds syntax rules of variation of insert sources (`INSERT INTO ~ SELECT ~`) to the document SQL Feature list.
> doc: reference of insert into ~ select.

- docs/sql-features.md
This PR adds syntax rules of simple built-in functions (e.g., `CURRENT_TIMESTAMP`) to the document SQL Feature list.
> doc: reference of built-in functions.

- docs/sql-features.md
This PR adds  syntax rules of temporal literal values (e.g., `TIMESTAMP '1970-1-1 12:34:56'`) to the document SQL Feature list.
> doc: reference of temporal value literals.

- docs/sql-features.md
This PR adds syntax rules of `BETWEEN` and `IN` predicate to the document SQL Feature list.
> docs: reference of `BETWEEN` and `IN`.

- docs/sql-features.md
This PR adds syntax rules of query binary operators (e.g., `UNION`) to the document SQL Feature list.
> docs: reference of query binary operators like `UNION`.

- docs/sql-features.md
This PR removes restriction notes from syntax rules of `DEFAULT VALUES` clause in `INSERT` statement in the document SQL Feature list.
> docs: reference of `INSERT INTO ~ DEFAULT VALUES`.

- docs/sql-features.md
This PR adds syntax rules of rest of set operators (`EXCEPT`, `INTERSECT`) to the document SQL Feature list.
> docs: reference of rest query set operators (`EXCEPT`, `INTERSECT`).

- docs/sql-features.md
This PR removes restriction notes from syntax rules of `LIMIT` clause in the document SQL Feature list.
> docs: reference of `LIMIT` without restrictions.

- docs/sql-features.md
This PR adds syntax rules of case expressions to the document SQL Feature list.
Note that this also includes the rules of case abbreviations like `COALESCE` and `NULLIF`.
> docs: reference of case expressions (`CASE`, `COALESCE`, and `NULLIF`).

- docs/sql-features.md
This PR adds a syntax rule of PostgreSQL-style cast (`expr::type`) to SQL feature list.
Note that, this feature has been worked correct since `1.0.0-BETA5`.
> docs: reference of PostgreSQL-style cast.

- docs/sql-features.md
This PR adds a syntax rule of BLOB/CLOB types to SQL feature list.
> docs: available SQL syntax for BLOB features.

- dist/install/install.sh
Tsurugi が主にサポートしている Ubuntu では、インストールディレクトリの下に `lib` ディレクトリを作成し、そこに共有ライブラリファイルを配置しますが、
RHEL 派生 Linux ディストリビューション等では、これが `lib64` ディレクトリとなり、サーバインストール時に `lib` ディレクトリを作成しませんが、
インストールスクリプトが `lib` ディレクトリがある前提で記述されているためファイルコピーが失敗します。
関連案件: project-tsurugi/tsurugi-issues#1066
この問題に対処する修正です。
ファイルコピーが失敗するときに、 cp コマンドがエラーにならず `lib` という名前のファイルとしてコピーしてしまい、より後段でエラーとなります。この問題に気づきやすくするように、 cp コマンドでコピー先の指定がディレクトリでないときにはそこでエラーとするような変更も入れてあります。
> dist: fix install.sh to work even if libdir is not "lib"

- docs/sql-features.md
This PR describes grammar rules of documentation comments (`/** ... */`).
> docs: add syntax rule for documentation comments.

- docs/sql-features.md
This pull request updates the documentation in `docs/sql-features.md` to clarify the usage of positional placeholders in SQL syntax.
> docs(compiler): add docs about positional placeholders.

- docs/config-parameters.md
新しく増えた構成パラメータ (tsurugi.ini ファイル `[cc]` セクションの `index_restore_threads`) に関する説明の追加です。
関連: project-tsurugi/tsurugi-issues#1239
> docs: add shirakami parallel recovery thread num setting
